language: ruby
rvm:
  - 1.9.2

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role manguezal SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database manguezal_ideias_test;' -U manguezal postgres"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0
# uncomment this line if your project needs to run something other than `rake`:
script: "bundle exec rake db:migrate && bundle exec rspec spec && bundle exec cucumber"

notifications:
  email:
    recipients: 
      - luiz@engage.is
      - daniel@powertothecrowd.com
  
